
services:

  db:
    image: mariadb:latest
    container_name: maria_db
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: brice
      MARIADB_DATABASE: sails
      MARIADB_USER: sails
      MARIADB_PASSWORD: sails
    volumes: 
      - ./mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: brice
    ports:
      - "8090:80"

  sails:
    build:
      context: ./restapi
    volumes:
      - ./restapi:/app
    working_dir: /app
    image: sails

    depends_on:
      - db
    environment:
      DB_HOST: maria_db
      DB_USER: sails
      DB_PASSWORD: sails
      DB_NAME: sails
    ports:
    - "1337:1337"
    #command: sails new restapi --no-frontend
    command: sails lift --hookTimeout=80000
    #command: nodemon -L app.js --ignore node_modules --ignore .tmp
    #command: node app.js
    #command: npm install

  frontapp:
    build:
      context: ./front
    volumes:
      - ./front:/app
      - /app/node_modules
    working_dir: /app
    image: frontapp
    ports:
    - "4100:4100"

    command: npm run dev
